name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
  uses: actions/setup-java@v4
  with:
    distribution: temurin
    java-version: '21'

      - name: Lint & Unit tests
  run: ./gradlew --stacktrace --info lint test

      - name: Assemble Debug
  run: ./gradlew --stacktrace --info :app:assembleDebug

      - name: Upload debug APK
  uses: actions/upload-artifact@v4
  with:
      - name: app-debug
    path: app/build/outputs/apk/debug/*.apk
    if-no-files-found: error

      - name: Upload build outputs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            app/build/outputs/**
            **/reports/**
          if-no-files-found: warn

