name: Android CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Env diag
        run: |
          echo "Java:"; java -version
          echo "Gradle wrapper:"; ./gradlew -v
          echo "Git SHA: $GITHUB_SHA"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Lint & Unit tests
        run: ./gradlew --stacktrace --info lint test

      - name: Assemble Debug
        run: ./gradlew --stacktrace --info :app:assembleDebug


      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
      - name: Upload build outputs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            app/build/outputs/**
            **/reports/**
          if-no-files-found: warn

